# Generated by Django 5.1 on 2024-08-13 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва компанії')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса компанії')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефонний номер')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Електронна пошта')),
            ],
            options={
                'verbose_name': 'Компанія',
                'verbose_name_plural': 'Компанії',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва країни')),
            ],
            options={
                'verbose_name': 'Країна',
                'verbose_name_plural': 'Країни',
            },
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Одиниця виміру')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='Скорочення')),
            ],
            options={
                'verbose_name': 'Одиниця виміру',
                'verbose_name_plural': 'Одиниці виміру',
            },
        ),
        migrations.CreateModel(
            name='NomenclatureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Група номенклатури')),
            ],
            options={
                'verbose_name': 'Група номенклатури',
                'verbose_name_plural': 'Групи номенклатури',
            },
        ),
        migrations.CreateModel(
            name='NomenclatureStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Статус номенклатури')),
            ],
            options={
                'verbose_name': 'Статус номенклатури',
                'verbose_name_plural': 'Статуси номенклатури',
            },
        ),
        migrations.CreateModel(
            name='NomenclatureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип номенклатури')),
            ],
            options={
                'verbose_name': 'Тип номенклатури',
                'verbose_name_plural': 'Типи номенклатури',
            },
        ),
        migrations.CreateModel(
            name='Opers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature', models.CharField(max_length=200, verbose_name='Номенклатура')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна закупу')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна продажу')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість')),
                ('company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Компанія')),
                ('warehouse', models.CharField(blank=True, max_length=200, null=True, verbose_name='Склад')),
                ('workshop', models.CharField(blank=True, max_length=200, null=True, verbose_name='Цех')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Година')),
                ('document_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер документа')),
                ('operation', models.CharField(choices=[('1', 'Прихід товару'), ('2', 'Реалізація товару'), ('3', 'Списання товару')], max_length=1, verbose_name='Операція')),
            ],
            options={
                'verbose_name': 'Операція',
                'verbose_name_plural': 'Операції',
            },
        ),
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип ціни')),
            ],
            options={
                'verbose_name': 'Тип ціни',
                'verbose_name_plural': 'Типи цін',
            },
        ),
        migrations.CreateModel(
            name='GoodsIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.company', verbose_name='Компанія')),
            ],
            options={
                'verbose_name': 'Реалізація товару',
                'verbose_name_plural': 'Реалізації товару',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.company', verbose_name='Компанія')),
            ],
            options={
                'verbose_name': 'Поступлення товару',
                'verbose_name_plural': 'Поступлення товару',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва виробника')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.country', verbose_name='Країна')),
            ],
            options={
                'verbose_name': 'Виробник',
                'verbose_name_plural': 'Виробники',
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва номенклатури')),
                ('article', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Артикул')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Штрих-код')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='nomenclature_images/', verbose_name='Зображення')),
                ('min_stock', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Мінімальний залишок')),
                ('max_stock', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Максимальний залишок')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Знижка')),
                ('external_system_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код для зовнішньої системи')),
                ('characteristics', models.JSONField(blank=True, null=True, verbose_name='Характеристика номенклатури')),
                ('base_measurement_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_measurement_unit', to='mainapp.measurementunit', verbose_name='Базова одиниця виміру')),
                ('country_of_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.country', verbose_name='Країна походження')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.manufacturer', verbose_name='Виробник')),
                ('measurement_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_unit', to='mainapp.measurementunit', verbose_name='Одиниця виміру')),
                ('warehouse_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_unit', to='mainapp.measurementunit', verbose_name='Складська одиниця')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.nomenclaturegroup', verbose_name='Група номенклатури')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.nomenclaturestatus', verbose_name='Статус номенклатури')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.nomenclaturetype', verbose_name='Тип номенклатури')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатури',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна закупівлі')),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mainapp.goodsreceipt')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.nomenclature', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Позиція поступлення',
                'verbose_name_plural': 'Позиції поступлення',
            },
        ),
        migrations.CreateModel(
            name='GoodsIssueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна продажу')),
                ('goods_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mainapp.goodsissue')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.nomenclature', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Позиція реалізації',
                'verbose_name_plural': 'Позиції реалізації',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Постачальник')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.country', verbose_name='Країна')),
            ],
            options={
                'verbose_name': 'Постачальник',
                'verbose_name_plural': 'Постачальники',
            },
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.supplier', verbose_name='Постачальник'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.supplier', verbose_name='Постачальник'),
        ),
        migrations.AddField(
            model_name='goodsissue',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.supplier', verbose_name='Покупець'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва складу')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Розташування')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='mainapp.company', verbose_name='Компанія')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склади',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва цеху')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Розташування')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='mainapp.company', verbose_name='Компанія')),
            ],
            options={
                'verbose_name': 'Цех',
                'verbose_name_plural': 'Цехи',
            },
        ),
    ]
